[package]
name = "qr_code"
description = "QR code encoder in Rust, support structured append (data in multiple qrcodes)"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2018"
authors = ["kennytm <kennytm@gmail.com>", "Riccardo Casatta <riccardo.casatta@gmail.com>"]
keywords = ["qrcode"]
repository = "https://github.com/RCasatta/qr_code"
readme = "README.md"
documentation = "http://docs.rs/qr_code"
exclude = [
    ".travis.yml", ".gitignore", "test-data/**"
]

[dependencies]
image = { version = "0.23", default-features = false, optional = true }  # remove use bmp-monochrome
checked_int_cast = "1"  # remove rust 1.34 support try_from

[dev-dependencies]
image = "0.23"  # remove

[features]
default = ["image", "svg"]
bench = []
svg = []

[[bin]]
name = "qrencode"

[[example]]
name = "encode_image"
required-features = ["image"]

[[example]]
name = "encode_string"

[[example]]
name = "encode_svg"
required-features = ["svg"]
