name: Fuzz

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:

  fuzz:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: [decode_check, encode, split_merge_rt]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache-fuzz
        with:
          path: |
            ~/.cargo/bin
            fuzz/target
            target
          key: cache-${{ matrix.target }}-${{ hashFiles('**/Cargo.toml','**/Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo install cargo-fuzz
        if: steps.cache-fuzz.outputs.cache-hit != 'true'
      - run: cargo +nightly fuzz run ${{ matrix.target }} -- -max_total_time=60
