name: Test and lint

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:

  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rust: [stable, nightly, 1.48.0]

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test --all --all-features
      - run: cargo run --example encode_string
      - run: cargo run --example encode_bmp --features bmp
      - run: cargo run --example decode_bmp --features bmp,decode

  cosmetics:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings
